name: init_tasks_example
description: Example app-init tasks wired with @Init annotations.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  init_tasks:
    path: ../init_tasks

dev_dependencies:
  build_runner: ^2.4.0
  dart_flutter_team_lints: ^1.0.0
  init_tasks_builder:
    path: ../init_tasks_builder
